site_name: "dry-validation documentation"
repo_url: https://github.com/dry-rb/dry-validation
edit_uri: edit/master/docs/
copyright: "Copyright &copy; 2015-2019 dry-rb team"
docs_dir: docs
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Schemas: schemas.md
  - Rules: rules.md
  - Messages: messages.md
  - Macros: macros.md
  - External Dependencies: external-dependencies.md
  - Extensions: extensions.md
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'teal'
  logo: 'images/dry-rb.png'
markdown_extensions:
  - admonition
  - codehilite
